---
sidebar: sidebar 
permalink: index.html 
keywords: interoperability matrix tool, imt, ONTAP SAN Host Simplified, 
summary: NetApp 互通性對照表工具（ IMT ）是網路型應用程式。IMT 可讓您搜尋符合 NetApp 所指定標準和要求的 NetApp 產品和元件組態。 
---
= 互通性對照表工具總覽
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp 互通性對照表工具（ IMT ）是網路型應用程式。IMT 可讓您搜尋符合 NetApp 所指定標準和要求的 NetApp 產品和元件組態。IMT 維護組態的儲存庫、並提供使用者友好的介面、方便存取支援的組態資訊。

您可以使用下列其中一種標準瀏覽器、從 NetApp 支援網站存取 IMT ：

* Windows：
+
** Chrome N 和 N-1
** Mozilla Firefox N 和 N-1
+

NOTE: N 代表最新版本。

** Internet Explorer 11 和 Edge


* Mac ：
+
** Chrome N 和 N-1
** Mozilla Firefox N 和 N-1
** Safari 8 及更新版本


+

NOTE: 互通性對照表工具接受 URL 連結、並提供標準以簡化特定使用案例。當您按一下其他工具的連結來開啟 IMT 時、您可能會進入遊樂場頁面、而非首頁、並預先選擇解決方案和某些元件。





== 開始使用互通性對照表工具

互通性對照表工具（ IMT ）是一種網路型應用程式、您可以使用不同的解決方案、組態、元件和類別來搜尋產品的相容性。

爲了便於瀏覽和清楚起見，此工具分爲三個頁面： * 輸入條件 * 、 * 優化搜索條件 * 和 * 結果 * 。您必須在第一頁輸入搜尋條件。根據您的搜尋條件、您可以在 * 精簡搜尋條件 * 頁面中檢視產品的相容性。本主題將快速說明如何使用 IMT 。

您可以在 * 結果 * 頁面中檢視結果。使用此工具、您可以搜尋元件、進行選擇、建置條件、以及檢視產品的相容性。

您可以完成下列工作：

[cols="25,65"]
|===
| 使用此頁面 ... | 您可以執行這些工作... 


| 輸入條件 | 輸入搜尋條件、然後搜尋解決方案、元件、組態和類別。如果您知道解決方案名稱、可以使用 * ONTAP SAN 主機簡體 * 或 * 解決方案搜尋 * 功能來搜尋解決方案。如果您知道元件名稱、可以使用 * 清單和尋找 * 或 * 進階搜尋 * 功能來搜尋元件。 


| 精簡搜尋條件 | 針對產品的相容解決方案、元件、組態和類別、找出更明確的是或否答案。您可以選擇使用 *Change Criteria * 或 * 嘗試不同的方法 * 來變更您在第一頁輸入的初始條件。將篩選條件套用至每個類別的元件、以找出最適合您產品的組態。使用 *Clear All* 或 *undo* 圖示移除您套用的篩選條件。 


| 結果 | 按一下 * 繼續 * 、 *>* 圖示或第二頁的分割器後、請檢視 * 結果 * 頁面。您可以檢視組態的元件、附註和歷程詳細資料、排序搜尋結果、檢視您選取的搜尋準則、修改搜尋準則、篩選搜尋結果、以及將搜尋結果匯出至 Microsoft Excel 工作表。 
|===


== 使用互通性對照表工具首頁

互通性對照表工具（ IMT ）首頁可讓您使用 * 簡化的 ONTAP SAN 主機 * 、 * 解決方案搜尋、清單與尋找 * 、以及 * 進階搜尋 * 。

您可以使用 * 設定為預設 * 星號、將這些選項中的任何一個設為預設搜尋。當您按一下任一選項時、相關頁面會開啟以探索相容的組態。


NOTE: 若要尋找先前儲存的搜尋、您可以使用 * 儲存的搜尋 * 功能表。如果您找不到所需的組態、請按一下「 * 找不到組態？ * 」功能表、然後回報問題。
