---
sidebar: sidebar 
permalink: working-with-solution-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: 您可以搜尋不同的儲存解決方案、並從搜尋條件中新增或移除解決方案。您可以使用「解決方案搜尋」頁面中的搜尋文字方塊來搜尋特定解決方案。「解決方案搜尋」欄位會顯示經常存取的解決方案。 
---
= 使用解決方案搜尋
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
您可以搜尋不同的儲存解決方案、並從搜尋條件中新增或移除解決方案。您可以使用 * 解決方案搜尋 * 頁面中的搜尋文字方塊來搜尋特定的解決方案。經常存取的解決方案會顯示在 * 解決方案搜尋 * 欄位中。



== 關於這項工作

「解決方案搜尋 * 」頁面包含 * 解決方案目錄 * 索引標籤和 * 對應助理 * 索引標籤。在 *Mapping Assistant* （映射助手）選項卡中，您可以選擇 *Map by Category* （按類別映射）或 *Map by Solution* （按解決方案映射）來查看選定解決方案的類別。



=== 解決方案目錄

在 * 解決方案目錄 * 索引標籤上、您可以使用篩選列 * 篩選解決方案 * 。

如果您想要納入這類組態、您也可以選擇 * 包含所需的 PVR 、 EOS 和 Obsolete 組態 * 。



=== 地圖繪製助理

以下是兩種工作區域模式：

* * 依類別對應 * ：您可以從列出的類別中選取類別、並啟用包含所選類別的所有解決方案、有效的解決方案位於清單頂端。您可以選擇新增單一或多個已啟用的解決方案。您可以使用 * 搜尋類別 * 文字方塊來搜尋特定類別。
* * 依解決方案對應 * ：您可以從列出的解決方案中選取解決方案、並啟用包含所選解決方案的所有解決方案、有效的解決方案位於清單頂端。您可以選擇新增單一或多個已啟用的解決方案。您可以使用 * 搜尋解決方案 * 文字方塊來搜尋特定類別。


如果您想要納入這類組態、您也可以選擇 * 包含所需的 PVR 、 EOS 和 Obsolete 組態 * 。

完成後、您可以在 * 所選儲存解決方案 * 下查看您所選取的項目。* 按一下檢視精簡搜尋條件 * 或 * 跳至結果 * 。



=== 引導式搜尋

* 引導式搜尋 * 會在您選擇解決方案時啟用。「 * 引導式搜尋 * 」提供引導式工作流程、可進一步調整條件。



== 步驟

. 按一下首頁的 * 解決方案搜尋 * 。
. 選取您要使用的檢視：
+
.. 按一下 * 專家檢視 * 以查看進階條件選項。
.. 按一下 * 導覽檢視 * 以查看簡化和導引條件選項。


. 在 * 新手檢視 * 中、選取所顯示的搜尋條件選項：
+
.. 單擊 * Skip* （跳過）可移至下一個組件，而無需進行選擇。您可以視需要按一下 *unski* 返回元件。
.. 在前五個選項之後、按一下 * 顯示更多 * 以繼續細化您的搜尋條件。您可以按一下「 * 顯示更少 * 」返回上一個檢視。
.. 完成後、請按一下 * 檢視結果 * 以查看搜尋條件所支援的組態。


. 在 * 專家檢視 * 中、選取您要用於各種元件的搜尋條件。我們建議您從左移至右移、因為每個選擇都會精簡其餘條件。您不需要為每個元件進行選擇。
+
.. 完成後、請按一下 * 檢視結果 * 以查看搜尋條件所支援的組態。


. 您也可以在 * 解決方案搜尋 * 中執行下列動作：
+
.. 按一下書籍圖示以檢視適用於您所選項目的原則和準則。
.. 按一下鏈結圖示、為您的選項產生可共享的 URL 、供您與他人分享。
.. 選取復原圖示以清除所有您選擇的項目、然後重新開始。


. 在結果畫面中、您可以執行下列動作：
+
.. 檢視有關您組態的詳細資料、警示和資訊通知。
.. 按一下星號圖示、將此搜尋設為我的最愛。命名並說明組態。這會變成儲存的搜尋、可從「儲存的搜尋」功能表中檢視。您也可以在此處訂閱組態、以便在變更時通知您。如果您訂閱、您也會在 * 訂閱 * 功能表下看到這項資訊。
.. 將游標暫留在 * 建置端點對端點檢視上方 * 、即可找到其他支援的解決方案。
.. 按一下 * 如果 * 、即可變更元件並探索其他相容選項。



