---
sidebar: sidebar 
permalink: working-with-ontap-san-host-solutions-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: 檢查 ONTAP 版本和 Flash 或 Fabric 儲存版本組合的相容性。您可以進一步調整每個相關元件的相容性搜尋 
---
= 使用 ONTAP SAN 主機簡化搜尋
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
檢查 ONTAP 版本和 Flash 或 Fabric 儲存版本組合的相容性。您可以進一步調整每個相關元件的相容性搜尋。



== 關於這項工作

您可以檢查 SAN 上的 Flash 或 Fabric 儲存裝置與您要使用的 ONTAP 版本和其他相關元件之間的相容性。您可以選擇 * 專家檢視 * 或 * 新手檢視 * 。


NOTE: 按一下 * 設為預設 * 選項、即可在您開啟 IMT 時自動開啟 * ONTAP SAN 主機 Simplified * 搜尋。



== 步驟

. 從首頁按一下 * ONTAP SAN 主機 Simplified * 。
. 選取您要使用的檢視：
+
.. 按一下 * 專家檢視 * 以查看進階條件選項。
.. 按一下 * 導覽檢視 * 以查看簡化和導引條件選項。


. 在 * 新手檢視 * 中、選取所顯示的搜尋條件選項。
+
.. 單擊 * Skip* （跳過）可移至下一個組件，而無需進行選擇。您可以視需要按一下 *unski* 返回元件。
.. 完成後、請按一下 * 檢視結果 * 以查看搜尋條件所支援的組態。


. 在 * 專家檢視 * 中、選取您要用於各種元件的搜尋條件。我們建議您從左移至右移、因為每個選擇都會精簡其餘條件。您不需要為每個元件進行選擇。
+
.. 完成後、請按一下 * 檢視結果 * 以查看搜尋條件所支援的組態。


. 您也可以在 * ONTAP SAN 主機 Simplified * 中執行下列動作：
+
.. 按一下書籍圖示以檢視適用於您所選項目的原則和準則。
.. 按一下鏈結圖示、為您的選項產生可共享的 URL 、供您與他人分享。
.. 選取復原圖示以清除所有選項、然後重新開始。


. 在結果畫面中、您可以執行下列動作：
+
.. 檢視有關您組態的詳細資料、警示和資訊通知。
.. 按一下星號圖示、將此搜尋設為我的最愛。命名並說明組態。這會變成儲存的搜尋、可從 * 儲存的搜尋 * 功能表檢視。您也可以在此處訂閱組態、以便在變更時通知您。如果您訂閱、您也會在 * 訂閱 * 功能表下看到這項資訊。
.. 將游標暫留在 * 建置端點對端點檢視上方 * 、即可找到其他支援的解決方案。
.. 按一下 * 如果 * 、即可變更元件並探索其他相容選項。



